api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
  path('v1/vote/', views.CreateVoteView.as_view(), name='create_vote'),
]

base/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
app_name = 'base'

urlpatterns = [
  path('', views.TopicListView.as_view(), name='top'),
  path('terms/', TemplateView.as_view(template_name='base/terms.html'), name='terms'),
  path('policy/', TemplateView.as_view(template_name='base/policy.html'), name='policy'),
  path('about/', TemplateView.as_view(template_name='base/about.html'), name='about'),
]

mysite/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
import base

from thread.sitemaps import TopicSitemap, CategorySitemap
from base.sitemaps import BaseSitemap

sitemaps = {
    'topic': TopicSitemap,
    'category': CategorySitemap,
    'base': BaseSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('base.urls')),
    path('thread/', include('thread.urls')),
    path('api/', include('api.urls')),
    path('search/', include('search.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.SearchResultView.as_view(), name='result'),
]

thread/urls.py
from django.urls import path

from . import views
app_name = 'thread'

urlpatterns = [
  path('create_topic/', views.TopicCreateView.as_view(), name='create_topic'),
  # path('<int:pk>/', views.TopicDetailView.as_view(), name='topic'),
  path('<int:pk>/', views.TopicAndCommentView.as_view(), name='topic'),
  path('category/<str:url_code>/', views.CategoryView.as_view(), name='category'),
  
  #3/14
  # コメントをしようとしたらnameとmessageが出てくるはずだが、コメントのボタンしか出てこない
  #おそらく、line8を消して、TopicDetailViewを消すか、下に移動させればできそう
  #3/15
  #コメント投稿してもエラーが出なくなった。しかし、user_nameは投稿できたが、messageが投稿できなかった
]

base/models.py
from django.db import models

# Create your models here.

thread/models.py
from django.db import models

class TopicManager(models.Manager):
    # Topic操作に関する処理を追加
    pass

class CommentManager(models.Manager):
    # Comment操作に関する処理を追加
    pass

class CategoryManager(models.Manager):
    # Category操作に関する処理を追加
    pass

class Category(models.Model):
    name = models.CharField(
        'カテゴリー名',
        max_length=50,
    )
    url_code = models.CharField(
        'URLコード',
        max_length=50,
        null=True,
        blank=False,
        unique=True,
    )
    sort=models.IntegerField(
        verbose_name='ソート',
        default=0,
    )
    objects = CategoryManager

    def __str__(self):
        return self.name

class Topic(models.Model):
    user_name = models.CharField(
        'お名前',
        max_length=30,
        null=True,
        blank=False,
    )
    title = models.CharField(
        'タイトル',
        max_length=255,
        null = False,
        blank = False,
    )
    message = models.TextField(
        verbose_name='本文',
        null=True,
        blank=False,
    )
    category = models.ForeignKey(
        Category,
        verbose_name='カテゴリー',
        on_delete=models.PROTECT,
        null=True,
        blank=False,
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )
    modified = models.DateTimeField(
        auto_now=True,
    )
    objects = TopicManager()

    def __str__(self):
        return self.title

class Comment(models.Model):
    id = models.BigAutoField(
        primary_key=True,
    )
    no = models.IntegerField(
        default=0,
    )
    user_name = models.CharField(
        'お名前',
        max_length=30,
        null=True,
        blank=False,
    )
    topic = models.ForeignKey(
        Topic,
        on_delete=models.PROTECT,
    )
    message = models.TextField(
        verbose_name='投稿内容'
    )
    pub_flg = models.BooleanField(
        default=True,
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )
    objects = CommentManager()

    def __str__(self):
        return '{}-{}'.format(self.topic.id, self.no)

class VoteManager(models.Manager):
    def create_vote(self, ip_address, comment_id):
        vote = self.model(
            ip_address=ip_address,
            comment_id = comment_id,
        )
        try:
            vote.save()
        except:
            return False
        return True

class Vote(models.Model):
    comment = models.ForeignKey(
        Comment,
        on_delete=models.CASCADE,
        null=True,
    )
    ip_address = models.CharField(
        'IPアドレス',
        max_length=50,
    )

    objects = VoteManager()

    def __str__(self):
        return '{}-{}'.format(self.comment.topic.title, self.comment.no)


# Create your models here.

base/views.py
from django.shortcuts import render
# from django.http import HttpResponse
# from django.template import loader
from django.views.generic import TemplateView, ListView

from thread.models import Topic

def top(request):
  # template = loader.get_template('base/top.html')
  ctx = {'title': '失敗投稿掲示板'}
  # return HttpResponse(template.render(ctx,request))
  return render(request, 'base/top.html', ctx)

class TopView(TemplateView):
  template_name = 'base/top.html'

  def get_context_data(self, **kwargs):
    ctx = super().get_context_data(**kwargs)
    ctx['title'] = '失敗談掲示板'
    return ctx

class TopicListView(ListView):
    template_name = 'base/top.html'
    # model = Topic
    queryset = Topic.objects.order_by('-created')
    context_object_name = 'topic_list'



# Create your views here.

templates/base/about.html
{% extends 'base/base.html' %}
{% block title %}このサイトはなに？ - {{ block.super }}{% endblock %}
{% block content %}
<div class="ui grid stackable">
    <div class="eleven wide column">
        <div class="ui breadcrumb">
            <a href="{% url 'base:top' %}" class="section">TOP</a>
            <i class="right angle icon divider"></i>
            <a class="active section">このサイトはなに？</a>
        </div>
        <div class="ui segment">
            <div class="content">
                <div class="header"><h3>このサイトはなに？</h3></div>
                <p>創設者：水谷 兆による失敗を語り合う掲示板です。</p>
                <!-- <p>このサイトはDjangoのサンプルアプリです。</p>
                <p>今回は失敗掲示板を作成しました。</p> -->
                <p>今日あったあなたの失敗を投稿して共有しましょう。</p>
                <p>あなたの失敗を書くことで、あなた自身はもちろんのこと、投稿を見た第三者も救われることになると思います。</p>
            </div>
        </div>
    </div>
    {% include 'base/sidebar.html' %}
</div>
{% endblock %}

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-language" content="ja">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    {% block meta_tag %}{% endblock %}
    <link href="{% static 'css/semantic.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}
    <title>
        {% block title %}失敗談掲示板{% endblock %}
    </title>
</head>
<body>
    <div class="ui stackable inverted menu">
        <a href="{% url 'base:top' %}" class="header item">
          失敗談掲示板
        </a>
        <a href="{% url 'base:about' %}" class="item">
            このサイトはなに？
        </a>
        <a class="item" href="{% url 'thread:create_topic' %}">
            トピック作成
        </a>
        <div class="right menu">
            <a class="item">
                Log in
            </a>
            <a class="item">
                Sign up
            </a>
        </div>
    </div>
    
    <div class="ui container" style="min-height:100vh;">
        {% block content %}
        {% endblock %}
    </div>
    <div class="ui inverted stackable footer segment">
        <div class="ui container center aligned">
            <div class="ui horizontal inverted small divided link list">
                <a href="{% url 'base:top' %}" class="item">© 2021 失敗談掲示板</a>
                <a href="{% url 'base:terms' %}" class="item">利用規約</a>
                <a href="{% url 'base:policy' %}" class="item">プライバシーポリシー</a>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/semantic.js' %}"></script>
    {% block js %}{% endblock %}
</body>

templates/base/dark.html
{% extends 'base/base.html' %}
<script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.7/lib/darkmode-js.min.js"></script>
<script>
    new Darkmode().showWidget();
</script>

templates/base/pagination.html
{% if is_paginated %}
<div class="ui basic segment center aligned">
    <div class="ui pagination menu">
    <!--左矢印-->
    {% if page_obj.has_previous %}
        <a class="item" href="?p={{page_obj.previous_page_number}}"><i class="chevron left icon"></i></a>
    {% else %}
        <a class="disabled item"><i class="chevron left icon"></i></a>
    {% endif %}
    <!--//左矢印-->
    <!--ページ番号-->
    {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
            <a class="disabled item">{{link_page}}</a>
        {% else %}
            <a class="item" href="?p={{link_page}}">{{link_page}}</a>
        {% endif %}
    {% endfor %}
    <!--//ページ番号-->
    <!--右矢印-->
    {% if page_obj.has_next %}
        <a class="item" href="?p={{page_obj.next_page_number}}"><i class="chevron right icon"></i></a>
    {% else %}
        <a class="disabled item"><i class="chevron right icon"></i></a>
    {% endif %}
    <!--//右矢印-->
    </div>
</div>
{% endif %}

templates/base/policy.html
{% extends 'base/base.html' %}
{% block title %}プライバシーポリシー - {{ block.super }}{% endblock %}
{% block content %}
<div class="ui grid stackable">
    <div class="eleven wide column">
        <div class="ui breadcrumb">
            <a href="{% url 'base:top' %}" class="section">TOP</a>
            <i class="right angle icon divider"></i>
            <a class="active section">プライバシーポリシー</a>
        </div>
        <div class="ui segment">
            <div class="content">
                <div class="header"><h3>プライバシーポリシー</h3></div>
                <p>リボ払い利用の方は強制退出</p>
                <p>スマイル(0円)</p>
                <p>自分探しは勝手にやってください</p>
                <p>ヴィーガンを押し付けないでください</p>
            </div>
        </div>
    </div>
    {% include 'base/sidebar.html' %}
</div>
{% endblock %}

templates/base/sidebar.html
{% load threadtags %}
<div class="five wide column">
  <form action="{% url 'search:result' %}" method="GET">
    <div class="ui action input" style="width: 100%;">
      <input type="text" placeholder="検索" name='q'>
      <button type="submit" class="ui button"><i class="search icon"></i></button>
    </div>
  </form>
  <div class="ui items">
      <div class="item">
        <a href="{% url 'thread:create_topic' %}" class="ui fluid teal button">トピックを作成</a>
      </div>
  </div>
  <div class="ui segment">
      <div class="content">
        <div class="header"><h4>カテゴリー</h4></div>
        {% categorytag %}
      </div>
  </div>
</div>

templates/base/terms.html
{% extends 'base/base.html' %}
{% block title %}利用規約 - {{ block.super }}{% endblock %}
{% block content %}

<div class="ui grid stackable">
    <div class="eleven wide column">
        <div class="ui breadcrumb">
            <a href="{% url 'base:top' %}" class="section">TOP</a>
            <i class="right angle icon divider"></i>
            <a class="active section">利用規約</a>
        </div>
        <div class="ui segment">
            <div class="content">
                <div class="header"><h3>利用規約</h3></div>
                <p>失敗は成功の元です。失敗の数だけ成功に近づけます。</p>
                <p>今日あったあなたの失敗をつぶやいて、どうすれば成功に繋ぐことができるかみんなで投稿し合いましょう。</p>
                <p>...........</p>
            </div>
        </div>
    </div>
    {% include 'base/sidebar.html' %}
</div>
{% endblock %}

templates/base/top.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}失敗を成功にする掲示板 - {{ block.super }}{% endblock %}
{% block content %}
<div class="ui grid stackable">
    <div class="eleven wide column">
        <div class="ui breadcrumb">
            <a class="active section">TOP</a>
        </div>
        <div class="ui segment">
            <div class="content">
                <div class="header"><h3>新着トピック</h3></div>
                <div class="ui divided items">
                    {% for topic in topic_list %}
                    <div class="item">
                        <div class="content">
                            <div class="header">
                                <a href="{% url 'thread:topic' pk=topic.id %}"><h4>{{topic.title}}</h4></a>
                            </div>
                            <div class="meta">
                                <span class="name">{{topic.user_name}}</span>
                                <span class="date">{{topic.created}}</span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% include 'base/sidebar.html' %}
</div>
{% endblock %}